<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Models\Person.fs" />
        <Compile Include="Repositories\MongoDbRepository.fs" />
        <Compile Include="Api\Handlers.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
    </ItemGroup>

</Project>
